# ----------- Build Stage ------------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy toàn bộ source
COPY . .

# Publish project
RUN dotnet publish -c Release -o /app

# ----------- Runtime Stage ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copy từ build stage
COPY --from=build /app .

# Chạy ứng dụng
ENTRYPOINT ["dotnet", "LAB03.dll"]
